<main class="landing-page">
  <nav class="landing-nav glass-card" aria-label="<?=__('Navigasi utama','Main navigation')?>">
    <a class="landing-brand" href="/"><span class="brand-orb"><img src="/assets/img/logo-simit-putih.png" alt="Logo SIMIT"></span><span><strong>SIMIT</strong><small>IT Operations Hub</small></span></a>
    <div class="landing-links"><a href="#fitur"><?=__('Fitur','Features')?></a><a href="#alur"><?=__('Cara kerja','How it works')?></a><a href="#tentang"><?=__('Tentang','About')?></a></div>
    <a class="landing-login" href="/login"><?=__('Masuk aplikasi','Sign in')?> <span>→</span></a>
  </nav>

  <section class="landing-hero" id="tentang">
    <div class="hero-copy">
      <span class="landing-kicker"><i></i><?=__('Sistem operasional tim IT','IT team operations system')?></span>
      <h1><?=__('Kelola teknologi','Manage technology')?> <em><?=__('dalam satu ruang kerja.','in one workspace.')?></em></h1>
      <p><?=__('SIMIT menyatukan inventaris perangkat, software, tugas, persetujuan, laporan, notifikasi, dan komunikasi tim agar pekerjaan IT lebih terukur dan mudah dilacak.','SIMIT brings device inventory, software, tasks, approvals, reports, notifications, and team communication into one measurable workspace.')?></p>
      <div class="hero-actions"><a class="landing-primary" href="/login"><?=__('Buka SIMIT','Open SIMIT')?> <span>↗</span></a><a class="landing-secondary" href="#fitur"><span class="play">▶</span><?=__('Lihat cara kerjanya','See how it works')?></a></div>
      <div class="trust-row"><div><strong>2</strong><span><?=__('Role terarah','Focused roles')?></span></div><div><strong>7+</strong><span><?=__('Modul terintegrasi','Integrated modules')?></span></div><div><strong>24/7</strong><span><?=__('Riwayat terlacak','Traceable history')?></span></div></div>
    </div>
    <div class="hero-visual" aria-label="<?=__('Pratinjau antarmuka dashboard SIMIT','SIMIT dashboard interface preview')?>">
      <div class="orb orb-one"></div><div class="orb orb-two"></div>
      <div class="dashboard-3d" id="dashboardPreview">
        <div class="demo-sidebar"><div class="demo-logo"><img src="/assets/img/logo-simit-putih.png" alt=""><b>SIMIT</b></div><?php foreach(['dashboard','pc','perangkat','software','tugas','laporan'] as $i=>$icon):?><span class="demo-nav <?=$i===0?'active':''?>"><?=nav_icon($icon)?></span><?php endforeach;?></div>
        <div class="demo-main"><header><div><small>OPERATIONS OVERVIEW</small><strong><?=__('Selamat datang kembali','Welcome back')?></strong></div><span class="demo-avatar">AR</span></header><div class="demo-stats"><article><i><?=nav_icon('pc')?></i><span>PC Aktif</span><b>24</b><small>+2 bulan ini</small></article><article><i><?=nav_icon('tugas')?></i><span>Tugas Berjalan</span><b>08</b><small>3 prioritas</small></article><article><i><?=nav_icon('software')?></i><span>Software</span><b>16</b><small>Semua tercatat</small></article></div><div class="demo-grid"><article class="demo-chart"><div><b><?=__('Kondisi inventaris','Inventory health')?></b><span>96% <?=__('baik','healthy')?></span></div><div class="bars"><i style="--h:45%"></i><i style="--h:68%"></i><i style="--h:54%"></i><i style="--h:88%"></i><i style="--h:72%"></i><i style="--h:94%"></i><i style="--h:80%"></i></div></article><article class="demo-tasks"><b><?=__('Tugas terbaru','Recent tasks')?></b><p><i></i><span>Update software Lab 1<small>Dikerjakan</small></span></p><p><i></i><span>Periksa PC resepsionis<small>Tersedia</small></span></p><p><i></i><span>Backup konfigurasi<small>Selesai</small></span></p></article></div></div>
      </div>
      <div class="floating-chip chip-one"><span>✓</span><div><b><?=__('Data tersinkron','Data organized')?></b><small><?=__('Semua perubahan terlacak','Every change is traceable')?></small></div></div>
      <div class="floating-chip chip-two"><span><?=nav_icon('chat')?></span><div><b><?=__('Chat internal','Internal chat')?></b><small><?=__('Koordinasi tanpa pindah aplikasi','Coordinate without switching apps')?></small></div></div>
    </div>
  </section>

  <section class="landing-section" id="fitur"><div class="section-heading"><span><?=__('APA YANG DIKELOLA','WHAT IT MANAGES')?></span><h2><?=__('Satu sistem untuk seluruh pekerjaan operasional IT.','One system for every IT operation.')?></h2><p><?=__('Dibangun untuk alur kerja nyata: data masuk, tugas dikerjakan, hasil diverifikasi, dan seluruh aktivitas tercatat.','Built for real workflows: capture data, complete tasks, verify results, and preserve every activity.')?></p></div><div class="feature-grid">
    <?php $features=[['pc',__('Inventaris perangkat','Device inventory'),__('Catat spesifikasi PC, lokasi, kondisi, dan perangkat pendukung dalam struktur yang mudah dicari.','Track PC specifications, locations, condition, and supporting devices in a searchable structure.')],['software','Software',__('Kelola aplikasi, versi, masa penggunaan, serta tugas instalasi atau penghapusan otomatis.','Manage applications, versions, usage periods, and automatic installation or removal tasks.')],['tugas',__('Tugas & persetujuan','Tasks & approval'),__('Tugas bersama dapat diklaim, dikumpulkan dengan bukti, lalu diperiksa Admin sebelum selesai.','Shared tasks can be claimed, submitted with evidence, and reviewed by Admin before completion.')],['laporan',__('Laporan operasional','Operational reports'),__('Ringkasan inventaris, kondisi aset, software, pengguna, dan riwayat pekerjaan siap dicetak.','Inventory, asset health, software, users, and work history summarized for reporting.')],['chat',__('Chat & notifikasi','Chat & notifications'),__('Koordinasikan pekerjaan langsung dan buka notifikasi menuju konteks tugas atau percakapan terkait.','Coordinate directly and open notifications in the related task or conversation context.')],['audit',__('Audit aktivitas','Activity audit'),__('Perubahan penting tersimpan sebagai jejak kerja agar pengelolaan lebih transparan dan akuntabel.','Important changes remain traceable for transparent, accountable management.')]]; foreach($features as $n=>$f):?><article class="feature-card glass-card"><span class="feature-number">0<?=$n+1?></span><i><?=nav_icon($f[0])?></i><h3><?=e($f[1])?></h3><p><?=e($f[2])?></p><a href="/login"><?=__('Lihat di aplikasi','View in app')?> →</a></article><?php endforeach;?>
  </div></section>

  <section class="workflow-section" id="alur"><div class="workflow-copy"><span class="landing-kicker"><i></i><?=__('ALUR KERJA','WORKFLOW')?></span><h2><?=__('Dari data menjadi tindakan, tanpa kehilangan konteks.','From data to action, without losing context.')?></h2><p><?=__('SIMIT menghubungkan kondisi inventaris dengan pekerjaan tim. Status software dapat menghasilkan tugas, hasil pekerjaan masuk ke antrean ACC, dan notifikasi membawa pengguna langsung ke halaman yang relevan.','SIMIT connects inventory conditions with team work. Software status can create tasks, submissions enter approval, and notifications take users directly to the relevant page.')?></p><a class="landing-primary" href="/login"><?=__('Jelajahi aplikasi','Explore the app')?> →</a></div><div class="workflow-steps">
    <article><span>01</span><div><b><?=__('Catat & pantau','Record & monitor')?></b><p><?=__('Admin dan User memperbarui inventaris serta software sesuai kondisi aktual.','Admin and User update inventory and software to reflect real conditions.')?></p></div></article>
    <article><span>02</span><div><b><?=__('Kerjakan tugas','Complete the task')?></b><p><?=__('Ambil tugas bersama atau selesaikan pekerjaan yang sudah memiliki PIC.','Claim a shared task or complete work assigned to a PIC.')?></p></div></article>
    <article><span>03</span><div><b><?=__('Kirim bukti & ACC','Submit evidence & approve')?></b><p><?=__('Hasil dan lampiran diperiksa Admin sebelum menjadi riwayat selesai.','Results and attachments are reviewed by Admin before entering completed history.')?></p></div></article>
    <article><span>04</span><div><b><?=__('Lacak & laporkan','Track & report')?></b><p><?=__('Dashboard, notifikasi, audit, dan laporan menjaga semua pihak tetap mengetahui progres.','Dashboards, notifications, audit, and reports keep everyone aligned.')?></p></div></article>
  </div></section>

  <section class="role-section"><div class="section-heading"><span><?=__('DIRANCANG UNTUK KOLABORASI','DESIGNED FOR COLLABORATION')?></span><h2><?=__('Dua role, satu sumber informasi.','Two roles, one source of truth.')?></h2></div><div class="role-grid"><article class="role-card admin"><span><?=nav_icon('akun')?></span><small>ADMIN</small><h3><?=__('Kontrol dan verifikasi','Control and verification')?></h3><ul><li><?=__('Kelola akun pengguna','Manage user accounts')?></li><li><?=__('Buat dan distribusikan tugas','Create and distribute tasks')?></li><li><?=__('ACC hasil pekerjaan','Approve work results')?></li><li><?=__('Pantau laporan dan audit','Monitor reports and audit')?></li></ul></article><article class="role-card user"><span><?=nav_icon('profile')?></span><small>USER</small><h3><?=__('Eksekusi dan pembaruan','Execution and updates')?></h3><ul><li><?=__('Perbarui inventaris dan software','Update inventory and software')?></li><li><?=__('Ambil serta kerjakan tugas','Claim and complete tasks')?></li><li><?=__('Unggah hasil pekerjaan','Upload work results')?></li><li><?=__('Berkomunikasi melalui chat','Communicate through chat')?></li></ul></article></div></section>

  <section class="landing-cta"><img src="/assets/img/logo-simit-putih.png" alt="Logo SIMIT"><span><?=__('SIAP MELIHAT LEBIH DEKAT?','READY FOR A CLOSER LOOK?')?></span><h2><?=__('Masuk ke ruang kerja SIMIT.','Enter the SIMIT workspace.')?></h2><p><?=__('Akun aplikasi dibuat oleh Admin. Pengunjung portfolio tetap dapat menjelajahi halaman ini tanpa login.','Application accounts are created by an Admin. Portfolio visitors can explore this page without signing in.')?></p><a href="/login"><?=__('Menuju halaman login','Go to login')?> <b>→</b></a></section>
  <footer class="landing-footer"><a class="landing-brand" href="/"><span class="brand-orb"><img src="/assets/img/logo-simit-putih.png" alt=""></span><span><strong>SIMIT</strong><small>Sistem Inventaris dan Manajemen IT</small></span></a><p>© <?=date('Y')?> SIMIT · GTTC IT Division</p><div><a href="#fitur"><?=__('Fitur','Features')?></a><a href="#alur"><?=__('Cara kerja','How it works')?></a><a href="/login"><?=__('Masuk','Sign in')?></a></div></footer>
</main>
<script src="/assets/js/landing.js"></script>
