<?php use Simit\Core\{Auth,Csrf}; $user=Auth::user(); $current=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/'); ?>
<!doctype html><html lang="<?=e(lang())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script>if(localStorage.getItem('simit-theme')==='dark'||(!localStorage.getItem('simit-theme')&&matchMedia('(prefers-color-scheme:dark)').matches))document.documentElement.dataset.theme='dark'</script><title><?=e($title??'SIMIT')?> · SIMIT</title><meta name="description" content="Sistem Inventaris dan Manajemen IT GTTC"><link rel="icon" type="image/svg+xml" href="/assets/img/favicon.svg"><link rel="stylesheet" href="/assets/css/app.css"></head>
<link rel="stylesheet" href="/assets/css/theme.css"></head><body class="<?= $user?'app-shell':'auth-shell' ?>">
<?php if($user): ?>
<aside class="sidebar" id="sidebar"><a class="brand" href="/"><img src="/assets/img/logo-simit.png" alt="Logo SIMIT"><span><strong>SIMIT</strong><small>GTTC · IT Division</small></span></a><nav>
<?php $nav=[''=>__('Dashboard','Dashboard'),'pc'=>__('Inventaris PC','PC Inventory'),'perangkat'=>__('Perangkat Lain','Other Devices'),'software'=>'Software','tugas'=>__('Tugas IT','IT Tasks'),'chat'=>'Chat','laporan'=>__('Laporan','Reports')]; if(Auth::isAdmin())$nav=[''=>__('Dashboard','Dashboard'),'pc'=>__('Inventaris PC','PC Inventory'),'perangkat'=>__('Perangkat Lain','Other Devices'),'software'=>'Software','tugas'=>__('Tugas IT','IT Tasks'),'persetujuan'=>__('ACC Tugas','Task Approval'),'chat'=>'Chat','laporan'=>__('Laporan','Reports')]; foreach($nav as $href=>$label): $mc=$href==='chat'?unread_message_count((int)$user['id']):0; ?><a href="/<?=$href?>" class="<?=($href===''?$current==='':str_starts_with($current,$href))?'active':''?>"><span class="nav-icon"><?=nav_icon($href?:'dashboard')?></span><?=e($label)?><?php if($mc>0):?><b class="count-badge"><?=$mc?></b><?php endif;?></a><?php endforeach; ?>
<a href="/profil" class="<?=str_starts_with($current,'profil')?'active':''?>"><span class="nav-icon"><?=nav_icon('profile')?></span><?=__('Profil Saya','My Profile')?></a><?php if(Auth::isAdmin()): ?><a href="/akun" class="<?=str_starts_with($current,'akun')?'active':''?>"><span class="nav-icon"><?=nav_icon('akun')?></span><?=__('Akun','Accounts')?></a><a href="/audit" class="<?=str_starts_with($current,'audit')?'active':''?>"><span class="nav-icon"><?=nav_icon('audit')?></span>Audit</a><?php endif; ?></nav><div class="sidebar-foot"><?php if($user['avatar_stored_name']??null):?><img class="avatar avatar-photo" src="/foto-profil/<?=$user['id']?>" alt=""><?php else:?><div class="avatar"><?=e(strtoupper(substr($user['name'],0,1)))?></div><?php endif;?><div><strong><?=e($user['name'])?></strong><small><?=e(ucfirst($user['role']))?></small></div><form method="post" action="/logout"><?=Csrf::field()?><button class="icon-btn" aria-label="<?=__('Keluar','Sign out')?>"><?=icon('logout')?></button></form></div></aside>
<main><header class="topbar"><button class="icon-btn menu-btn" id="menuButton" aria-label="<?=__('Buka navigasi','Open navigation')?>"><?=icon('menu')?></button><div><p class="eyebrow"><?=__('Sistem operasional','Operations system')?></p><h1><?=e($title??'SIMIT')?></h1></div><div class="top-actions"><form method="post" action="/language" class="lang-switch"><?=Csrf::field()?><input type="hidden" name="lang" value="<?=lang()==='id'?'en':'id'?>"><button type="submit" class="text-btn"><?=lang()==='id'?'EN':'ID'?></button></form><button class="icon-btn" id="themeButton" aria-label="<?=__('Ubah tema','Toggle theme')?>"><?=icon('theme')?></button><span class="date"><?=date('d M Y')?></span><a class="icon-btn <?=unread_notification_count((int)$user['id'])?'has-count':''?>" href="/notifikasi" aria-label="<?=__('Notifikasi','Notifications')?>"><?=icon('bell')?><?php if($nc=unread_notification_count((int)$user['id'])):?><b class="top-count"><?=$nc?></b><?php endif;?></a></div></header><section class="page">
<?php if($m=flash('success')):?><div class="alert success"><?=e($m)?></div><?php endif;if($m=flash('error')):?><div class="alert error"><?=e($m)?></div><?php endif;?><?=$content?></section></main>
<?php else: ?><div class="login-tools"><form method="post" action="/language"><?=Csrf::field()?><input type="hidden" name="lang" value="<?=lang()==='id'?'en':'id'?>"><button class="text-btn"><?=lang()==='id'?'EN':'ID'?></button></form><button class="icon-btn" id="themeButton" aria-label="<?=__('Ubah tema','Toggle theme')?>">◐</button></div><?=$content?><?php endif; ?>
<link rel="stylesheet" href="/assets/css/workflow.css"><link rel="stylesheet" href="/assets/css/task-table.css"><link rel="stylesheet" href="/assets/css/report-responsive.css"><link rel="stylesheet" href="/assets/css/report-print.css"><link rel="stylesheet" href="/assets/css/communication.css"><link rel="stylesheet" href="/assets/css/profile.css"><link rel="stylesheet" href="/assets/css/notification-links.css"><link rel="stylesheet" href="/assets/css/landing.css"><script src="/assets/js/app.js"></script><script src="/assets/js/theme-icon.js"></script><script src="/assets/js/task-table.js"></script></body></html>
<?php function icon(string $name):string{$icons=['dashboard'=>'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>','pc'=>'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/>','perangkat'=>'<path d="M12 2l9 5-9 5-9-5 9-5zM3 12l9 5 9-5M3 17l9 5 9-5"/>','software'=>'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M8 12h8M12 8v8"/>','tugas'=>'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/>','pemeriksaan'=>'<circle cx="11" cy="11" r="8"/><path d="M21 21l-4.3-4.3M8 11l2 2 4-4"/>','kegiatan'=>'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>','laporan'=>'<path d="M4 19V9M10 19V5M16 19v-8M22 19H2"/>','audit'=>'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/>','logout'=>'<path d="M10 17l5-5-5-5M15 12H3M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4"/>','menu'=>'<path d="M4 6h16M4 12h16M4 18h16"/>','bell'=>'<path d="M18 8a6 6 0 00-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>'];return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'.($icons[$name]??$icons['dashboard']).'</svg>';}

